# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43bc7e349f34208b5da749fcbd060fe38d1a5818813821ea87e0bc2c6e821c2679120c47ceac4ee29ff52124f56968ecaac8ea7782ea9f0e5d255caf7313db1e

test:
  secret_key_base: 65af53a4392e04c0a88b710bb26d5849bb3999c4abacd439d9afefc6938c5842d85bf89d1108116ca4b511845a83f450cbdd13fde62cb90c69b262d444430c20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
